.text.gen_huffman_table 0x1fd820 : { KEEP(patch.o (.text.gen_huffman_table)) }
.text.tinflate_partial : { KEEP(patch.o (.text.tinflate_partial)) }
.text.tinflate_write_objmem : { KEEP(patch.o (.text.tinflate_write_objmem)) }
.text.tinflate_read_objmem : { KEEP(patch.o (.text.tinflate_read_objmem)) }
.text.ucode_compressed_bin : { KEEP(patch.o (.data.ucode_compressed_bin)) }
.text.ucode_compressed_bin_len : { KEEP(patch.o (.data.ucode_compressed_bin_len)) }