LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= sljitLir.c

#LOCAL_CFLAGS:=-O2 -g -DSLJIT_CONFIG_AUTO=1
LOCAL_CFLAGS:=-O2 -g -DSLJIT_CONFIG_ARM_THUMB2=1
#LOCAL_CFLAGS:=-O2 -g -DSLJIT_CONFIG_ARM_THUMB2=1 -DSLJIT_VERBOSE=0 -DSLJIT_DEBUG=0

LOCAL_MODULE:= sljit

include $(BUILD_STATIC_LIBRARY)
