.text.dma_rx 0x8c69c : { ../wrapper/wrapper.o (.text.dma_rx) }
.text.dma_rxfill 0x8c6cc : { ../wrapper/wrapper.o (.text.dma_rxfill) }
.text.dngl_sendpkt 0x182750 : { ../wrapper/wrapper.o (.text.dngl_sendpkt) }
.text.printf 0x126f0 : { ../wrapper/wrapper.o (.text.printf) }
.text.wlc_mctrl_write 0x4df60 : { ../wrapper/wrapper.o (.text.wlc_mctrl_write) }
.text.wlc_bmac_mctrl 0x4F080 : { ../wrapper/wrapper.o (.text.wlc_bmac_mctrl)}
